version: 2
sources:
- name: mt4_live01_airbyte
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_orders
  - name: _airbyte_raw_ticks
  - name: _airbyte_raw_traderecord
